import 'package:get/get.dart';

class Localization extends Translations {
  @override
  Map<String, Map<String, String>> get keys => {
        'en_US': {
          'login/registration': 'Login/Registration',
          'enter_your_mobile': 'Enter your mobile',
          'mobile_no': 'Mobile No',
          // 'sign_up': 'Sign Up',
          'continue': 'Continue',
          'phone_number_verification': 'Phone Number Verification',
          'enter_the_code_sent_to': 'Enter the code sent to',
          'verify': 'Verify',
          'full_name': 'Full Name',
          'email': 'Email',
          'password': 'Password',
          'register': 'Register',
          'select_your_gender': 'Select your gender',
          'male': 'Male',
          'female': 'Female',
          'home': 'Home',
          'reservation': 'Reservation',
          'account': 'Account',
          'rate_us': 'Rate Us',
          'language': 'Language',
          'privacy_policy': 'Privacy Policy',
          'terms&conditions': 'Terms & Conditions',
          'logout': 'Logout',
        },
        'ar_SA': {
          'login/registration': 'تسجيل الدخول / التسجيل',
          'enter_your_mobile': 'أدخل هاتفك المحمول',
          'mobile_no': 'رقم الموبايل',
          // 'sign_up': 'اشتراك',
          'continue': 'استمر',
          'phone_number_verification': 'التحقق من رقم الهاتف',
          'enter_the_code_sent_to': 'أدخل الرمز المرسل إلى',
          'verify': 'يؤكد',
          'full_name': 'الاسم الكامل',
          'email': 'البريد الإلكتروني',
          'password': 'كلمة المرور',
          'register': 'يسجل',
          'select_your_gender': 'اختر جنسك',
          'male': 'الذكر',
          'female': 'أنثى',
          'home': 'الصفحة الرئيسية',
          'reservation': 'تحفظ',
          'account': 'الحساب',
          'rate_us': 'قيمنا',
          'language': 'لغة',
          'privacy_policy': 'سياسة الخصوصية',
          'terms&conditions': 'البنود و الظروف',
          'logout': 'تسجيل خروج',
        }
      };
}
